---
- name: APP | create folders
  file:
    path: "{{ app_root }}"
    state: directory

- name: APP | copy files
  copy:
    src: src/
    dest: "{{ app_root }}"

- name: APP | Install packages defined in a given package.json.
  npm:
    path: "{{ app_root }}"

- name: APP | Delete old version
  shell: "pm2 kill"
  tags:
    - deploy-app-pm2

- name: APP | Run app
  shell: pm2 start app.js --name {{ pm2_app_name }}
  args:
    chdir: "{{ app_root}}/app"
  tags:
    - deploy-app-pm2

- name: APP | pm2 systemd unit
  shell: pm2 startup systemd
  tags:
    - deploy-app-pm2

- name: APP | pm2 save app
  shell: pm2 save
  tags:
    - deploy-app-pm2
